#!groovy

pipeline {
  agent any
  stages {    
    stage('initialize') {
      steps {
        echo 'Initializing'
      }
    }        
    stage('Build') {
      steps {
        echo 'Building'
      }
    }              
    stage('Test') {
      steps {
        echo 'Testing'
      }
    }       
  }
}