#!groovy

pipeline {
  agent any
  environment{
    DEBUG_OUTPUT = 'false'
  }
  stages {    
    stage('initialize') {
      steps {
        echo "Initializing"
      }
    }        
    stage('Build') {
      steps {
        echo "Building"
      }
    }              
    stage('Test') {
      steps {
        echo "Testing"
      }
    }       
  }
}